"""honeybee radiance schedule command."""
import click
import sys
import logging
import os
import json

from ladybug.epw import EPW
from ladybug.datacollection import HourlyContinuousCollection
from ladybug.header import Header
from ladybug.datatype.generic import GenericType
from ladybug.analysisperiod import AnalysisPeriod


_logger = logging.getLogger(__name__)


@click.group(help='Commands to create and modify schedules.')
def schedule():
    pass


@schedule.command('epw-to-daylight-hours')
@click.argument(
    'epw', type=click.Path(exists=True, dir_okay=False, resolve_path=True))
@click.option('--folder', '-f', help='Output folder.', default='.', show_default=True)
@click.option(
    '--name', '-n', help='Output file name for schedule.',
    type=click.STRING, default='daylight_hours', show_default=True
)
def epw_to_daylight_hours(epw, folder, name):
    """Convert EPW to EN 17037 schedule as a CSV file and JSON file (DataCollection).

    This command generates a valid schedule for EN 17037, also known as daylight hours.
    Rather than a typical occupancy schedule, the daylight hours is half the year with
    the largest quantity of daylight. This is generated by sorting the EPW file by
    diffuse horizontal illuminance.

    \b
    Args:
        epw: Path to epw file.
    """
    try:
        epw_data = EPW(epw)
        diffuse_horizontal_illuminance = epw_data.diffuse_horizontal_illuminance
        _illuminance, indices = diffuse_horizontal_illuminance.highest_values(4380)
        values = ['1' if i in indices else '0' for i in range(8760)]

        if not os.path.isdir(folder):
            os.makedirs(folder)

        # write csv
        file_path = os.path.join(folder, '%s.csv' % name)
        with open(file_path, 'w') as fp:
            fp.write('\n'.join(values))

        # write json
        data_type = GenericType(
            'Schedule: Daylight Hours', unit='Occupancy', min=0, max=1)
        header = Header(
            data_type=data_type, unit='Occupancy',
            analysis_period=AnalysisPeriod())
        values = [int(v) for v in values]
        datacollection = HourlyContinuousCollection(header, values)

        json_path = os.path.join(folder, '%s.json' % name)
        with open(json_path, 'w') as fp:
            json.dump(datacollection.to_dict(), fp, indent=4)

    except Exception:
        _logger.exception('Failed to generate daylight hours schedule.')
        sys.exit(1)
    else:
        sys.exit(0)
