version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "Sphinx"
      - match:
          dependency_name: "sphinx-click"
      - match:
          dependency_name: "coveralls"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
