"""Dictionary of light path for each room in large_light_path_model.hbjson"""

room_light_path_dict = {
    'room_1': [
        ['__static_apertures__'],
        ['room_1_south'],
        ['__static_apertures__', 'room_2_east'],
        ['__static_apertures__', 'room_3-4_west', 'room_4_east'],
        ['__static_apertures__', 'room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_3-4_west', '__static_apertures__', 'room_5_west'],
        ['__static_apertures__', 'room_3-4_west', 'room_4-5', '__static_apertures__'],
        ['__static_apertures__', 'room_3-4_west', 'room_4-5', 'room_5_west'],
        ['__static_apertures__', 'room_3-4_east', 'room_4_east'],
        ['__static_apertures__', 'room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_3-4_east', '__static_apertures__', 'room_5_west'],
        ['__static_apertures__', 'room_3-4_east', 'room_4-5', '__static_apertures__'],
        ['__static_apertures__', 'room_3-4_east', 'room_4-5', 'room_5_west'],
        ['__static_apertures__', '__static_apertures__'],
        ['room_1-2', 'room_2_east'],
        ['room_1-2', 'room_3-4_west', 'room_4_east'],
        ['room_1-2', 'room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['room_1-2', 'room_3-4_west', '__static_apertures__', 'room_5_west'],
        ['room_1-2', 'room_3-4_west', 'room_4-5', '__static_apertures__'],
        ['room_1-2', 'room_3-4_west', 'room_4-5', 'room_5_west'],
        ['room_1-2', 'room_3-4_east', 'room_4_east'],
        ['room_1-2', 'room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['room_1-2', 'room_3-4_east', '__static_apertures__', 'room_5_west'],
        ['room_1-2', 'room_3-4_east', 'room_4-5', '__static_apertures__'],
        ['room_1-2', 'room_3-4_east', 'room_4-5', 'room_5_west'],
        ['room_1-2', '__static_apertures__']
    ],
    'room_2': [
        ['__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_1_south'],
        ['room_1-2', '__static_apertures__'],
        ['room_1-2', 'room_1_south'],
        ['room_2_east'],
        ['room_3-4_west', 'room_4_east'],
        ['room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['room_3-4_west', '__static_apertures__', 'room_5_west'],
        ['room_3-4_west', 'room_4-5', '__static_apertures__'],
        ['room_3-4_west', 'room_4-5', 'room_5_west'],
        ['room_3-4_east', 'room_4_east'],
        ['room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['room_3-4_east', '__static_apertures__', 'room_5_west'],
        ['room_3-4_east', 'room_4-5', '__static_apertures__'],
        ['room_3-4_east', 'room_4-5', 'room_5_west'],
        ['__static_apertures__']
    ],
    'room_3': [
        ['__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_1_south'],
        ['room_1-2', '__static_apertures__'],
        ['room_1-2', 'room_1_south'],
        ['room_2_east'],
        ['room_3-4_west', 'room_4_east'],
        ['room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['room_3-4_west', '__static_apertures__', 'room_5_west'],
        ['room_3-4_west', 'room_4-5', '__static_apertures__'],
        ['room_3-4_west', 'room_4-5', 'room_5_west'],
        ['room_3-4_east', 'room_4_east'],
        ['room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['room_3-4_east', '__static_apertures__', 'room_5_west'],
        ['room_3-4_east', 'room_4-5', '__static_apertures__'],
        ['room_3-4_east', 'room_4-5', 'room_5_west'],
        ['__static_apertures__']
    ],
    'room_4': [
        ['room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['room_3-4_west', '__static_apertures__', 'room_1_south'],
        ['room_3-4_west', 'room_1-2', '__static_apertures__'],
        ['room_3-4_west', 'room_1-2', 'room_1_south'],
        ['room_3-4_west', 'room_2_east'],
        ['room_3-4_west', '__static_apertures__'],
        ['room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['room_3-4_east', '__static_apertures__', 'room_1_south'],
        ['room_3-4_east', 'room_1-2', '__static_apertures__'],
        ['room_3-4_east', 'room_1-2', 'room_1_south'],
        ['room_3-4_east', 'room_2_east'],
        ['room_3-4_east', '__static_apertures__'],
        ['room_4_east'],
        ['__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_5_west'],
        ['room_4-5', '__static_apertures__'],
        ['room_4-5', 'room_5_west']
    ],
    'room_5': [
        ['__static_apertures__', 'room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_3-4_west', '__static_apertures__', 'room_1_south'],
        ['__static_apertures__', 'room_3-4_west', 'room_1-2', '__static_apertures__'],
        ['__static_apertures__', 'room_3-4_west', 'room_1-2', 'room_1_south'],
        ['__static_apertures__', 'room_3-4_west', 'room_2_east'],
        ['__static_apertures__', 'room_3-4_west', '__static_apertures__'],
        ['__static_apertures__', 'room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_3-4_east', '__static_apertures__', 'room_1_south'],
        ['__static_apertures__', 'room_3-4_east', 'room_1-2', '__static_apertures__'],
        ['__static_apertures__', 'room_3-4_east', 'room_1-2', 'room_1_south'],
        ['__static_apertures__', 'room_3-4_east', 'room_2_east'],
        ['__static_apertures__', 'room_3-4_east', '__static_apertures__'],
        ['__static_apertures__', 'room_4_east'],
        ['room_4-5', 'room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['room_4-5', 'room_3-4_west', '__static_apertures__', 'room_1_south'],
        ['room_4-5', 'room_3-4_west', 'room_1-2', '__static_apertures__'],
        ['room_4-5', 'room_3-4_west', 'room_1-2', 'room_1_south'],
        ['room_4-5', 'room_3-4_west', 'room_2_east'],
        ['room_4-5', 'room_3-4_west', '__static_apertures__'],
        ['room_4-5', 'room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['room_4-5', 'room_3-4_east', '__static_apertures__', 'room_1_south'],
        ['room_4-5', 'room_3-4_east', 'room_1-2', '__static_apertures__'],
        ['room_4-5', 'room_3-4_east', 'room_1-2', 'room_1_south'],
        ['room_4-5', 'room_3-4_east', 'room_2_east'],
        ['room_4-5', 'room_3-4_east', '__static_apertures__'],
        ['room_4-5', 'room_4_east'],
        ['__static_apertures__'],
        ['room_5_west']
    ],
    'room_6': [
        ['__static_apertures__', '__static_apertures__', 'room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_west', '__static_apertures__', 'room_1_south'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_west', 'room_1-2', '__static_apertures__'], 
        ['__static_apertures__', '__static_apertures__', 'room_3-4_west', 'room_1-2', 'room_1_south'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_west', 'room_2_east'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_west', '__static_apertures__'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_east', '__static_apertures__', 'room_1_south'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_east', 'room_1-2', '__static_apertures__'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_east', 'room_1-2', 'room_1_south'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_east', 'room_2_east'],
        ['__static_apertures__', '__static_apertures__', 'room_3-4_east', '__static_apertures__'],
        ['__static_apertures__', '__static_apertures__', 'room_4_east'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_west', '__static_apertures__', 'room_1_south'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_west', 'room_1-2', '__static_apertures__'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_west', 'room_1-2', 'room_1_south'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_west', 'room_2_east'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_west', '__static_apertures__'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_east', '__static_apertures__', 'room_1_south'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_east', 'room_1-2', '__static_apertures__'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_east', 'room_1-2', 'room_1_south'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_east', 'room_2_east'],
        ['__static_apertures__', 'room_4-5', 'room_3-4_east', '__static_apertures__'],
        ['__static_apertures__', 'room_4-5', 'room_4_east'],
        ['__static_apertures__', '__static_apertures__'],
        ['__static_apertures__', 'room_5_west'],
        ['room_5-6', '__static_apertures__', 'room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['room_5-6', '__static_apertures__', 'room_3-4_west', '__static_apertures__', 'room_1_south'],
        ['room_5-6', '__static_apertures__', 'room_3-4_west', 'room_1-2', '__static_apertures__'],
        ['room_5-6', '__static_apertures__', 'room_3-4_west', 'room_1-2', 'room_1_south'],
        ['room_5-6', '__static_apertures__', 'room_3-4_west', 'room_2_east'],
        ['room_5-6', '__static_apertures__', 'room_3-4_west', '__static_apertures__'],
        ['room_5-6', '__static_apertures__', 'room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['room_5-6', '__static_apertures__', 'room_3-4_east', '__static_apertures__', 'room_1_south'],
        ['room_5-6', '__static_apertures__', 'room_3-4_east', 'room_1-2', '__static_apertures__'],
        ['room_5-6', '__static_apertures__', 'room_3-4_east', 'room_1-2', 'room_1_south'],
        ['room_5-6', '__static_apertures__', 'room_3-4_east', 'room_2_east'],
        ['room_5-6', '__static_apertures__', 'room_3-4_east', '__static_apertures__'],
        ['room_5-6', '__static_apertures__', 'room_4_east'],
        ['room_5-6', 'room_4-5', 'room_3-4_west', '__static_apertures__', '__static_apertures__'],
        ['room_5-6', 'room_4-5', 'room_3-4_west', '__static_apertures__', 'room_1_south'],
        ['room_5-6', 'room_4-5', 'room_3-4_west', 'room_1-2', '__static_apertures__'],
        ['room_5-6', 'room_4-5', 'room_3-4_west', 'room_1-2', 'room_1_south'],
        ['room_5-6', 'room_4-5', 'room_3-4_west', 'room_2_east'],
        ['room_5-6', 'room_4-5', 'room_3-4_west', '__static_apertures__'],
        ['room_5-6', 'room_4-5', 'room_3-4_east', '__static_apertures__', '__static_apertures__'],
        ['room_5-6', 'room_4-5', 'room_3-4_east', '__static_apertures__', 'room_1_south'],
        ['room_5-6', 'room_4-5', 'room_3-4_east', 'room_1-2', '__static_apertures__'],
        ['room_5-6', 'room_4-5', 'room_3-4_east', 'room_1-2', 'room_1_south'],
        ['room_5-6', 'room_4-5', 'room_3-4_east', 'room_2_east'],
        ['room_5-6', 'room_4-5', 'room_3-4_east', '__static_apertures__'],
        ['room_5-6', 'room_4-5', 'room_4_east'],
        ['room_5-6', '__static_apertures__'],
        ['room_5-6', 'room_5_west']
    ]
}